/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StoragePanel.java
 *
 * Created on 7.10.2009, 22:21:45
 */
package tradeworld.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import tradeworld.Building;
import tradeworld.Factory;
import tradeworld.Goods;
import tradeworld.Player;
import tradeworld.Pos;
import tradeworld.Storage;

/**
 *
 * @author Petr Dluhoš
 */
public class StoragePanel extends javax.swing.JPanel {

    /**
     * Test main method
     * @param args
     */
    public static void main(String[] args) {
        JFrame frame1 = new JFrame("Storage frame");
        JFrame frame2 = new JFrame("Storage frame");



        Player player1 = new Player("Petr", null, 0, null);
        Player player2 = new Player("Kotuc", null, 0, null);
        Storage storage1 = new Storage(player1, new Pos(2.0, 5.0, 0), 50);
        Storage storage2 = new Storage(player1, new Pos(2.0, 5.0, 0), 50);
        Factory factory1 = new Factory(Building.Type.LUMBERJACK_CAMP, player1, new Pos(5.0, 5.0, 0));
        Factory factory2 = new Factory(Building.Type.WOODMILL, player1, new Pos(5.0, 5.0, 0));

        StoragePanel panel1 = new StoragePanel(storage1);
        StoragePanel panel2 = new StoragePanel(storage2);

        storage1.getPayload().addGoods(new Goods(Goods.Type.BOARD, 12, player1));
        storage2.getPayload().addGoods(new Goods(Goods.Type.BOARD, 47, player2));
        factory1.addStorage(storage1);
        factory1.addStorage(storage2);
        factory1.selectProductionChain(factory1.getProductionChains().get(0));
        factory2.addStorage(storage1);
        factory2.addStorage(storage2);
        factory2.selectProductionChain(factory2.getProductionChains().get(0));
        //  factory1.startWorking();
        //  factory2.startWorking();

        panel1.setStorage(storage1);
        panel2.setStorage(storage2);




        frame1.add(panel1);
        frame2.add(panel2);
        frame1.pack();
        frame2.pack();
        frame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame1.setVisible(true);
        frame2.setVisible(true);

        while (true) {
            factory1.doStep();

            factory2.doStep();
            panel1.updateIt();
            panel2.updateIt();
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(StoragePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }



    }

    /** Creates new form StoragePanel */
    public StoragePanel(Storage storage) {
        initComponents();
        setStorage(storage);
        updateIt();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPayload = new javax.swing.JList();

        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("jLabelName");

        jListPayload.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPayload);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelName;
    private javax.swing.JList jListPayload;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Storage storage;

    public void setStorage(Storage storage) {

        this.storage = storage;
    }

    public void updateIt() {

        jLabelName.setText(storage.getName() + " (" + storage.getOwner().getName() + ")" + System.currentTimeMillis());

        jListPayload.removeAll();

        jListPayload.setModel(new javax.swing.AbstractListModel() {

            public int getSize() {
                return storage.getPayload().getNumberOfGoodsTypes();
            }

            public Object getElementAt(int i) {
                Goods goods = storage.getPayload().getGoodsAt(i);
                return (goods.getType().toString() + " " + goods.getQuantity() + " (" + goods.getOwner().getName() + ")");
            }
        });

    }
}
