package tradeworld.gui;

import tradeworld.actions.BuildVehicleAction;
import javax.swing.DefaultListModel;
import tradeworld.Depot;
import tradeworld.Vehicle;

/**
 *
 * @author Petr Dluhoš
 */
public class DepotPanel extends SuperPanel {

    private final Depot depot;

    /**
     * Test main method
     * @param args
     */
//    public static void main(String[] args) {
//        JFrame frame = new JFrame("Depot frame");
//
//        DepotPanel panel = new DepotPanel(new Depot(Building.Type.TRUCK_DEPOT1, new Player("Petr", null, 0, null), new Pos(0.0, 0.0, 0.0)));
//
//        panel.update();
//
//        frame.add(panel);
//        frame.pack();
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setVisible(true);
//
//    }
    /** Creates new form DepotPanel
     * @param frame
     * @param depot 
     */
    public DepotPanel(Depot depot) {
        initComponents();
        this.depot = depot;
        update();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVehicles = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("jLabelName");

        jListVehicles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListVehicles);

        jButton1.setText("build truck");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getChaosFrame().scheduleAction(
                new BuildVehicleAction(depot, Vehicle.Type.SKODA120));        // TODO add your handling code here:
//        chaosFrame.scheduleAction(new BuildVehicleAction(depot, Vehicle.Type.SKODA120));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JList jListVehicles;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void update() {

        setName(depot.toString());

        jLabelName.setText("" + depot.getWorkingState());

        DefaultListModel defaultListModel = new DefaultListModel();
        if (depot.isEmpty()) {
            defaultListModel.addElement("<no vehicles>");
        } else {
            for (Vehicle vehicle : depot.getVehicles()) {
                defaultListModel.addElement(vehicle);
            }
        }
        jListVehicles.setModel(defaultListModel);

//        jListVehicles.removeAll();
//
//        jListVehicles.setModel(new javax.swing.AbstractListModel() {
//
//            public int getSize() {
//                return depot.getVehicles().size();
//            }
//
//            public Object getElementAt(int i) {
//                return depot.getVehicles().toArray()[i];
//            }
//        });
    }
}
