/*
 * DownPanel.java
 *
 * Created on 20. prosinec 2007, 14:03
 */
package tools;

/**
 *
 * @author  Kotuc
 */
public class DownPanel extends javax.swing.JPanel {

    private Download download;

    /** Creates new form DownPanel
     * @param download 
     */
    public DownPanel(Download download) {

        if (download == null) {
            throw new NullPointerException("download");
        }

        this.download = download;

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        fileLabel = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();

        fileLabel.setText("jLabel1");

        progressLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(progressLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void repaint() {
        if (progressBar != null) {
            progressBar.setValue(download.getProgress());
        }
        if (fileLabel != null) {
            fileLabel.setText(download.getTargetFile().getName());
        }
        if (progressLabel != null) {
            if (download.completed()) {
                progressLabel.setText("" + download.getTotalSize() + " completed");
            } else {
                progressLabel.setText("" + download.getCurrentSize() + " of " + download.getTotalSize());

            }
        }
        super.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
}
