/*
 * BoardPanel.java
 *
 * Created on 19. bøezen 2008, 18:24
 */

package towerdefence;

import java.awt.Dimension;
import java.awt.Graphics;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.vecmath.Point3d;

/**
 *
 * @author  Kotuc
 */
public class BoardPanel extends javax.swing.JPanel {
    
    /** Creates new form BoardPanel
     * @param board 
     */
    public BoardPanel(Board board) {
        this.board = board;
        initComponents();
        setPreferredSize(new Dimension(board.width, board.height));
        new Timer().schedule(new TimerTask() {

            @Override
            public void run() {
                repaint();
            }
        }, 100, 1);
    }

    private Unit putUnit;
    
    public void mousePut(Unit unit) {
        this.putUnit = unit;
    }
    
    private Board board;
    
    @Override
    public void paint(Graphics g) {
        board.paint(g);
        if (putUnit!=null) {
            putUnit.paint(g);
        }
//        super.paint(g);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
//        Tower tower = new Tower();
//        tower.setPos(new Point3d(evt.getX(), evt.getY(), 0));
//        board.put(tower);
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

            if (putUnit != null) {
                putUnit.setPos(new Point3d(evt.getX(), evt.getY(), 0));
                board.put(putUnit);
            }
            mousePut(Templates.TOWER1.clone());

    }//GEN-LAST:event_formMouseReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if (putUnit!=null) {
            putUnit.setPos(new Point3d(evt.getX(), evt.getY(), 0));
        }
    }//GEN-LAST:event_formMouseMoved
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
