/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StoragePanel.java
 *
 * Created on 7.10.2009, 22:21:45
 */
package tradeworld.gui;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import tradeworld.Building;
import tradeworld.Factory;
import tradeworld.Goods;
import tradeworld.Player;
import tradeworld.Pos;
import tradeworld.Storage;

/**
 *
 * @author Petr Dluhoš
 */
public class StoragePanel extends SuperPanel {

    /**
     * Test main method
     * @param args
     */
    public static void main(String[] args) {
        JFrame frame1 = new JFrame("Storage frame");
        JFrame frame2 = new JFrame("Storage frame");



        Player player1 = new Player("Petr", null, 0, null);
        Player player2 = new Player("Kotuc", null, 0, null);
        Storage storage1 = new Storage(player1, new Pos(2.0, 5.0, 0), 50);
        Storage storage2 = new Storage(player1, new Pos(2.0, 5.0, 0), 50);
        Factory factory1 = new Factory(Building.Type.LUMBERJACK_CAMP, player1, new Pos(5.0, 5.0, 0));
        Factory factory2 = new Factory(Building.Type.WOODMILL, player1, new Pos(5.0, 5.0, 0));



        storage1.getPayload().addGoods(new Goods(Goods.Type.BOARD, 12, player1));
        storage2.getPayload().addGoods(new Goods(Goods.Type.BOARD, 47, player2));
        factory1.addStorage(storage1);
        factory1.addStorage(storage2);
        factory1.selectProductionChain(factory1.getProductionChains().get(0));
        factory2.addStorage(storage1);
        factory2.addStorage(storage2);
        factory2.selectProductionChain(factory2.getProductionChains().get(0));
        //  factory1.startWorking();
        //  factory2.startWorking();

        StoragePanel panel1 = new StoragePanel(storage1);
        StoragePanel panel2 = new StoragePanel(storage2);

        frame1.add(panel1);
        frame2.add(panel2);
        frame1.pack();
        frame2.pack();
        frame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame1.setVisible(true);
        frame2.setVisible(true);

        while (true) {
            factory1.doStep();

            factory2.doStep();
            panel1.update();
            panel2.update();
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(StoragePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }



    }
    private final Storage storage;
    private final PayloadPanel payloadPanel;

    /** Creates new form StoragePanel */
    public StoragePanel(Storage storage) {
        initComponents();
        this.storage = storage;
        this.payloadPanel = new PayloadPanel(storage.getPayload());
        this.add(payloadPanel, BorderLayout.CENTER);
        update();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void update() {

        setName(storage.toString());
        payloadPanel.update();

//        DefaultListModel defaultListModel = new DefaultListModel();
//        for (Goods goods : storage.getPayload().getGoods()) {
//            defaultListModel.addElement(goods);
//        }
//        jListPayload.setModel(defaultListModel);

//        jListPayload.removeAll();
//
//        jListPayload.setModel(new javax.swing.AbstractListModel() {
//
//            public int getSize() {
//                return storage.getPayload().getNumberOfGoodsTypes();
//            }
//
//            public Object getElementAt(int i) {
//                Goods goods = storage.getPayload().getGoodsAt(i);
//                return (goods.getType().toString() + " " + goods.getQuantity() + " (" + goods.getOwner().getName() + ")");
//            }
//        });

    }
}
