package tradeworld.gui;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.vecmath.Point3d;
import tradeworld.Building;
import tradeworld.Depot;
import tradeworld.Goods;
import tradeworld.Player;
import tradeworld.Truck;
import tradeworld.Vehicle;

/**
 *
 * @author Petr Dluhoš
 */
public class VehiclePanel extends SuperPanel {

    /**
     * Test main method
     * @param args
     */
    public static void main(String[] args) {
        JFrame frame = new JFrame("Vehicle Panel");


        Player player1 = new Player("Petr", null, 0, null);
        Player player2 = new Player("Joan", null, 0, null);

        Truck truck = new Truck(player1, Vehicle.Type.STEAM_TRUCK, new Point3d());
        truck.getPayload().addGoods(new Goods(Goods.Type.FURNITURE, 3, player1));
        truck.getPayload().addGoods(new Goods(Goods.Type.WOOD, 1, player1));
        truck.getPayload().addGoods(new Goods(Goods.Type.WOOD, 1, player2));


        VehiclePanel panel = new VehiclePanel(truck);

        frame.add(panel);
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

    }
    private final Vehicle vehicle;
    private final PayloadPanel payloadPanel;

    /** Creates new form VehiclePanel */
    public VehiclePanel(Vehicle vehicle) {
        initComponents();
        this.vehicle = vehicle;
        this.payloadPanel = new PayloadPanel(vehicle.getPayload());
        this.add(payloadPanel, BorderLayout.CENTER);
        update();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        statusMessageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("set track");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_START);

        statusMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusMessageLabel.setText("jLabel1");
        add(statusMessageLabel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // select building for whatever :-D        // TODO add your handling code here:
        new Thread() {

            @Override
            public void run() {
                {
                    System.err.println("Select src depot");
                    Building selectBuilding = getChaosFrame().selectBuilding();
                    if (selectBuilding != null) {
                        vehicle.setSrcDepot((Depot) selectBuilding);
                        System.err.println("Src depot: " + selectBuilding);
                    } else {
                        System.err.println("cancelled");
                        return;
                    }
                }
                {
                    System.err.println("Select dest depot");
                    Building selectBuilding = getChaosFrame().selectBuilding();
                    if (selectBuilding != null) {
                        vehicle.setDestDepot((Depot) selectBuilding);
                        System.err.println("Dest depot set: " + selectBuilding);
                    } else {
                        System.err.println("cancelled");
                        return;
                    }
                }

            }
        }.start();        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel statusMessageLabel;
    // End of variables declaration//GEN-END:variables

    public void update() {

        setName(vehicle.toString());
        payloadPanel.update();
        statusMessageLabel.setText(vehicle.getStatusMessage());

//        jListPayload.removeAll();
//
//        jListPayload.setModel(new javax.swing.AbstractListModel() {
//
//            public int getSize() {
//                return vehicle.getPayload().getNumberOfGoodsTypes();
//            }
//
//            public Object getElementAt(int i) {
//                Goods goods = vehicle.getPayload().getGoodsAt(i);
//                return (goods.getType().toString() + " " + goods.getQuantity() + " (" + goods.getOwner().getName() + ")");
//            }
//        });


    }
}
