package tradeworld.gui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Koste
 */
public class MainPanel2 extends javax.swing.JPanel {

    private ChaosFrame chaosFrame;

    /** Creates new form MainPanel
     * @param chaosFrame
     */
    public MainPanel2(ChaosFrame chaosFrame) {
        this.chaosFrame = chaosFrame;
        initComponents();

        jTabbedPane1.addTab("",
                new ImageIcon(getClass().getResource("/icons/buildings.png")),
                new BuildingsPanel(chaosFrame), "Buildings");
        jTabbedPane1.addTab("",
                new ImageIcon(getClass().getResource("/icons/infrastructure.png")),
                new InfrastructurePanel(chaosFrame), "Infrastructure");
        jTabbedPane1.addTab("",
                new ImageIcon(getClass().getResource("/icons/vehicles.png")),
                new VehiclesPanel(), "Vehicles");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buildings.png"))); // NOI18N
        jButton2.setText("Buildings");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/infrastructure.png"))); // NOI18N
        jButton3.setText("Infrastructure");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vehicles.png"))); // NOI18N
        jButton4.setText("Vehicles");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        JFrame frame = new JFrame("Trade World - Main panel");

        InfrastructurePanel panel = new InfrastructurePanel(chaosFrame);

        frame.add(panel);
        frame.pack();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFrame frame = new JFrame("Trade World - Main panel");

        BuildingsPanel panel = new BuildingsPanel(chaosFrame);

        frame.add(panel);
        frame.pack();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        JFrame frame = new JFrame("Trade World - Main panel");

        VehiclesPanel panel = new VehiclesPanel();

        frame.add(panel);
        frame.pack();
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
