/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DepotPanel.java
 *
 * Created on 12.10.2009, 1:22:14
 */

package tradeworld.gui;

import javax.swing.JFrame;
import tradeworld.Building;
import tradeworld.Depot;
import tradeworld.Player;
import tradeworld.Pos;

/**
 *
 * @author Petr Dluhoš
 */
public class DepotPanel extends javax.swing.JPanel {

    /**
     * Test main method
     * @param args
     */
     public static void main(String[] args) {
        JFrame frame = new JFrame("Depot frame");

        DepotPanel panel = new DepotPanel(new Depot(Building.Type.TRUCK_DEPOT1, new Player("Petr", null, 0, null), new Pos(0.0, 0.0, 0.0)));

        panel.update();

        frame.add(panel);
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

     }

    /** Creates new form DepotPanel */
    public DepotPanel(Depot depot) {

        setDepot(depot);
        initComponents();
        update();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVehicles = new javax.swing.JList();

        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("jLabelName");

        jListVehicles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListVehicles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelName;
    private javax.swing.JList jListVehicles;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Depot depot;

    public void setDepot(Depot depot) {

        this.depot = depot;
    }

    public void update() {

        jLabelName.setText(depot.getType().toString() + " (" + depot.getOwner().getName() + ")");

        jListVehicles.removeAll();

        jListVehicles.setModel(new javax.swing.AbstractListModel() {

            public int getSize() {
                return depot.getVehicles().size();
            }
            public Object getElementAt(int i) {
                return depot.getVehicles().toArray()[i];
            }


        });


    }
}
