package tradeworld.gui;

/**
 *
 * @author Koste
 */
public class VehiclesPanel extends javax.swing.JPanel {

    /** Creates new form VehiclesPanel */
    public VehiclesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vehicles.png"))); // NOI18N
        jButton1.setText("Steam truck");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vehicles.png"))); // NOI18N
        jButton2.setText("Light truck");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vehicles.png"))); // NOI18N
        jButton3.setText("Skoda 120");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables

}
