/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DownloadInfoPanel.java
 *
 * Created on 16.3.2010, 10:07:23
 */
package tools;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Kotuc
 */
public class DownloadInfoPanel extends javax.swing.JPanel {

    /** Creates new form DownloadInfoPanel */
    public DownloadInfoPanel() {
        initComponents();
    }

    public void show(Download download) {

        //        image.setIcon(Toolkit.getDefaultToolkit().addAWTEventListener(null, WIDTH));
//            image.setIcon(new ImageIcon(new URL("http://www.google.cz/intl/en_com/images/logo_plain.png")));
//            image.setIcon(new ImageIcon(new URL("http://media.novinky.cz/221/202211-top_foto1-zlf25.jpg")));
//        download.getLink();
//        image.setText("okk");
//        System.err.println("get" + download.getLink());
        if (download.getLink().getThumbs().isEmpty()) {
            image.setIcon(null);
            image.setText("no thumb " + download.getLink().getTitle());
        } else {
            image.setIcon(new ImageIcon(download.getLink().getThumbs().get(0)));
            image.setText(""+download.getLink().getThumbs().get(0));
            System.out.println(""+download.getLink().getThumbs().get(0));
//            image.setText(null);

        }
        downloadName.setText(download.getTargetFile().getName());
        sourceUrl.setText(download.getSourceURL().toString());
        localFile.setText(download.getTargetFile().toString());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        downloadName = new javax.swing.JLabel();
        sourceUrl = new javax.swing.JLabel();
        localFile = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        downloadName.setText("download name");

        sourceUrl.setText("source URL");

        localFile.setText("target file");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadName, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
            .addComponent(sourceUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(localFile, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(downloadName)
                .addGap(1, 1, 1)
                .addComponent(sourceUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(localFile))
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);
        add(image, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        JFrame jFrame = new JFrame("Test");
        DownloadInfoPanel dip = new DownloadInfoPanel();
        dip.show(new Download(null, null));
        jFrame.add(dip);
        jFrame.pack();
        jFrame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel downloadName;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel localFile;
    private javax.swing.JLabel sourceUrl;
    // End of variables declaration//GEN-END:variables
}
