/*
 * DownPanel.java
 *
 * Created on 20. prosinec 2007, 14:03
 */
package tools;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.border.BevelBorder;


/**
 *
 * @author  Kotuc
 */
public class DownPanel extends javax.swing.JPanel {

    private Download download;

    /** Creates new form DownPanel
     * @param download 
     */
    public DownPanel(Download download) {

        if (download == null) {
            throw new NullPointerException("download");
        }

        this.download = download;

        myInitComponents();
//        initComponents();
    }

    private void myInitComponents() {

        setBorder(new BevelBorder(BevelBorder.RAISED));
        
        setLayout(new BorderLayout());
        
        progressBar = new JProgressBar();
        fileLabel = new JLabel();
        progressLabel = new JLabel();

        add(fileLabel, BorderLayout.NORTH);
        add(progressBar, BorderLayout.CENTER);
        add(progressLabel, BorderLayout.SOUTH);
        
                    
    }
    
    String units(long dataSize) {
        int tire = 0;
//        dataSize/=8;
        while (dataSize>10000) {
            dataSize/=1024;
            tire++;
        }
        String[] marks = new String[] {"B", "KB", "MB", "GB", "TB"};
        return ""+dataSize+marks[tire];
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        fileLabel = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();

        fileLabel.setText("jLabel1");

        progressLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(progressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void repaint() {
        if (progressBar != null) {
            progressBar.setValue(download.getProgress());
        }
        if (fileLabel != null) {
            fileLabel.setText(download.getTargetFile().getName());
        }
        if (progressLabel != null) {
            if (download.completed()) {
                progressLabel.setText("" + units(download.getTotalSize()) + " completed");
            } else {
                progressLabel.setText("" + units(download.getCurrentSize()) + " of " + units(download.getTotalSize())+
                        "; speed: "+units(download.getSpeed())+"/s");
            }
        }
        super.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
}
